baseURL: "http://example.org/"
languageCode: en-us
title: "Siddharth Nair"
relativeURLs: true
buildDrafts: false
canonifyURLs: false
enableGitInfo: true

pagination:
  pagerSize: 4

staticDir:
  - static
