main:

  - identifier: now
    name: Now
    url: /

  - identifier: writings
    name: Writings
    url: /writings/

  - identifier: projects
    name: Projects
    url: /projects/

  - identifier: stream
    name: Stream
    url: /stream/

  - identifier: library
    name: Library
    url: /library/

  # - identifier: about
  #   name: About
  #   url: /about/

  - identifier: notes
    name: Notes
    url: /notes/
