baseURL: "http://localhost:1313/"
buildDrafts: false

pagination:
  pagerSize: 4

staticDir:
  - static

server:
  headers:
    - for: "/giscus/**"
      values:
        Access-Control-Allow-Origin: "https://giscus.app"
        Access-Control-Allow-Methods: "GET, OPTIONS"
        Access-Control-Allow-Headers: "Access-Control-Request-Private-Network"
        Access-Control-Allow-Private-Network: "true"